name: Android Build & Release

on:
  push:
    branches: [ "master", "main" ]
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decode Keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keystore.jks

    - name: Build Signed APK
      run: |
        ./gradlew assembleRelease \
        -Pandroid.injected.signing.store.file=keystore.jks \
        -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
        -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
        -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

    - name: Upload Release
      uses: ncipollo/release-action@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        artifacts: "app/build/outputs/apk/release/*.apk"
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
